// Command scaffolder (C3): renders a starter command file that follows the
// project's command pattern (descriptor + run), ready to drop into a righthand
// commands dir and be auto-discovered.
//
// The template is strip-only TS (no enums / parameter properties / namespaces)
// and uses ONLY `import type` for its dependencies. `import type` is erased at
// load time under Node strip-only and Bun, so the rendered file imports cleanly
// from ANY location — the footprint commands dir, a temp smoke test, anywhere —
// with no runtime resolution of "../contracts.ts" required. See
// docs/wiki/learnings/node-strip-only-typescript-rejects-parameter-properties-enum.md
import { VERSION } from "./contracts.ts";

export interface ScaffoldOptions {
  name: string;
  description: string;
}

// kebab-case: lowercase letter, then lowercase/digits joined by single hyphens.
// Rejects path traversal (".." / "/"), underscores, and leading digits by
// construction — so a valid name can never escape the commands dir.
const NAME_RE = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

// Returns an error message for an invalid name, or null when valid.
export function validateName(name: string): string | null {
  if (!name) return "name is required";
  if (!NAME_RE.test(name)) {
    return `invalid name "${name}": use kebab-case (lowercase letters/digits, single hyphens; e.g. ci-status)`;
  }
  return null;
}

// Render a starter command file. Self-contained at runtime (type-only import).
export function renderCommand(opts: ScaffoldOptions): string {
  const name = opts.name;
  const desc = opts.description || `${name} command`;
  const summary = `${name}: stub — not yet implemented`;
  return [
    "// Generated by `righthand new`. Fill in run(); it is auto-discoverable",
    "// once it lives under a righthand commands dir. See the authoring guide.",
    'import type { ToolDescriptor, CommandContext, Envelope } from "../contracts.ts";',
    "",
    "export const descriptor: ToolDescriptor = {",
    `  name: ${JSON.stringify(name)},`,
    `  description: ${JSON.stringify(desc)},`,
    "  inputSchema: {",
    '    type: "object",',
    "    properties: {},",
    "    additionalProperties: false,",
    "  },",
    '  plugin: "@local",',
    '  costTier: "free",',
    "};",
    "",
    "// Stub handler — replace with real logic, keep the envelope shape.",
    "export async function run(ctx: CommandContext): Promise<Envelope> {",
    "  return {",
    "    ok: true,",
    `    command: ${JSON.stringify(name)},`,
    `    summary: ${JSON.stringify(summary)},`,
    "    result: null,",
    "    needs_human: null,",
    `    meta: { version: ${JSON.stringify(VERSION)}, duration_ms: 0, change_id: null, tokens_used: 0 },`,
    "  };",
    "}",
    "",
  ].join("\n");
}
